apiVersion: v1
kind: Secret
metadata:
  name: harbor-registry-secret
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJoYXJib3IuZGV2b3BzLmNpY2QudGVzdCI6eyJ1c2VybmFtZSI6InJvYm90JGRldm9wcy10ZXN0LTk4OTgrZnVzZS11c2VyLTEzIiwicGFzc3dvcmQiOiJMYlMxY2dsblU0ZGwwUmZTY2VKM1pnSlVRMWdUam14QSIsImF1dGgiOiJjbTlpYjNRa1pHVjJiM0J6TFhSbGMzUXRPVGc1T0N0bWRYTmxMWFZ6WlhJdE1UTTZUR0pUTVdObmJHNVZOR1JzTUZKbVUyTmxTak5hWjBwVlVURm5WR3B0ZUVFPSJ9fX0=
