apiVersion: v1
kind: Secret
metadata:
  name: harbor-registry-secret
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJoYXJib3IuZGV2b3BzLmNpY2QudGVzdCI6eyJ1c2VybmFtZSI6InJvYm90JGxpZy1kZW1vK2Z1c2UtdXNlci0yNiIsInBhc3N3b3JkIjoiZkUzWldmRDdkWXk0bXJDNUxaRUM0Z2k2SUplc3BGcmUiLCJhdXRoIjoiY205aWIzUWtiR2xuTFdSbGJXOHJablZ6WlMxMWMyVnlMVEkyT21aRk0xcFhaa1EzWkZsNU5HMXlRelZNV2tWRE5HZHBOa2xLWlhOd1JuSmwifX19
