apiVersion: v1
kind: Secret
metadata:
  name: harbor-registry-secret
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJoYXJib3IuZGV2b3BzLmNpY2QudGVzdCI6eyJ1c2VybmFtZSI6InJvYm90JGRldm9wcy10ZXN0LTk4OTgrZnVzZS11c2VyLTI2IiwicGFzc3dvcmQiOiJBZWVEcXZCYVNHbENrMTVhOWN1aDZmNUhYWTZmM29MeiIsImF1dGgiOiJjbTlpYjNRa1pHVjJiM0J6TFhSbGMzUXRPVGc1T0N0bWRYTmxMWFZ6WlhJdE1qWTZRV1ZsUkhGMlFtRlRSMnhEYXpFMVlUbGpkV2cyWmpWSVdGazJaak52VEhvPSJ9fX0=
